name: example
description: Protobuf example.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  grpc: ^3.2.4
  json_annotation: ^4.8.1
  protobuf: ^3.1.0
  

dev_dependencies:
  json_serializable: ^6.7.1

